# ───────────
# E*TRADE API
# ───────────
etrade:
  consumer_key: "<YOUR_CONSUMER_KEY>"
  consumer_secret: "<YOUR_CONSUMER_SECRET>"
  oauth_token_path: "auth_tokens.json"

# ───────────
# Trade sizing & rules
# ───────────
trading:
  min_credit: 0.15
  max_width: 1.0
  max_delta: 0.25
  profit_target_pct: 0.5    # 50% of credit
  stop_loss_multiplier: 2   # pay 2× credit

# ───────────
# Schedule times (24h ET)
# ───────────
schedule:
  entry_mid_morning: "09:45"
  entry_close_window: "14:30"
  force_close: "15:55"
# ───────────